#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpimonitor
# Required-Start:    $networking $remote_fs
# Required-Stop:     $networking $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: RPi-Monitor daemon
# Description:       Daemon for RPi serlf monitoring
### END INIT INFO

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 
   exit 1
fi

# Source function library.
. /lib/lsb/init-functions

DAEMON="/usr/local/rpimonitor/rpimonitord"
PIDFILE="/var/run/rpimonitord.pid"

[ -x $DAEMON ] || exit 0

start() {
    log_daemon_msg "Starting RPi-Monitor" "rpimonitord"
    $DAEMON -b
    status=$?
    log_end_msg $status
}

stop() {
    log_daemon_msg "Stopping RPi-Monitor" "rpimonitord"
    for pid in $(cat $PIDFILE); do
        kill -9 $pid > /dev/null 2>&1
      done
    status=$?
    log_end_msg $status
}

restart() {
    echo -n "Restarting RPi-Minitor"
    stop
    sleep 2
    start
}

case "$1" in
    start)
    	start
    ;;
    stop)
    	stop
    ;;
    restart)
    	restart
    ;;
    *)
    	echo "Usage: $0 {start|stop|restart}"
    ;;
esac

exit 0
